// Copyright (c) 2026 Project Hawnmun. All rights reserved.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace HawnmunGameplayTags
{
	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Key_SpaceBar)
	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Key_LeftShift)

	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Key_LButton)
	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Key_RButton)

	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Key_1)
	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Key_2)
	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Key_3)

	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cost_Sprint)

	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stamina_RegenBlocked)
	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stamina_Full)
	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead)

	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Strafing)
	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_UnderAttack)
	PROJECTH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_State_Unblockable)
}